### ISSUE TITLE
Insert all the data in the DB

### ISSUE THREAD

**Issue by hedi-sassi** [hedi-sassi/rbnb_db_project#23]
Insert data after the cleaning part (see TODO's in Main.scala)

**Comment by hedi-sassi** [comment]
Hello,
For this issue we will not need to insert the data via the program. We can insert the data by importing the csv files directly in SQLDevelopper and then select where to put the different columns.
It's faster than writing a program just for inserting the data.... 

It may also be a good idea to wait for the first feedback before inserting anything in the database.

**Comment by cgiaccar** [comment]
Yeah you are right, but I'm not sure I'm able to use SQLDeveloper 😅

For the feedback, do we know when are we going to receive it?

**Comment by hedi-sassi** [comment]
Don't worry for SQLDev a friend taught us how to insert the data.
And for the feedback I don't know when they will give them but meanwhile we can start coding the main program (UI, back-end functions for SQL query building etc... )
